config/routes.rb
Manage::Application.routes.draw do
  resources :sites, :roles do
    resources :users 
    resources :tasks do
      resources :comments
    end
  end
  root :to => "sites#index"
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :body, :task_id
  # relationships
  belongs_to :task
end

app/models/role.rb
class Role < ActiveRecord::Base
  attr_accessible :role
  # relationships
  has_many :users

end

app/models/site.rb
class Site < ActiveRecord::Base
  attr_accessible :title
  # relationships
  has_many :users
  has_many :tasks


  def complete_tasks
    ta = []
    tasks.each do |t|
      if t.status.status === "approved"
        ta << t
      end
    end
    ta
  end
  def incomplete_tasks
    ta = []
    tasks.each do |t|
      if t.status.status != "approved"
        ta << t
      end
    end
    ta
  end
end

app/models/status.rb
class Status < ActiveRecord::Base
  attr_accessible :status
  # relationships
  has_many :tasks

end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :body, :site_id, :title, :status_id
  # relationships
  belongs_to :site
  belongs_to :status
  has_many :comments



  def row_color
    case status.status
    when "defined"
      "#F2DEDE"
    when "in-progress"
      "#D9EDF7"
    when "completed"
      "#FCF8E3"
    when "approved"
      "#DFF0D8"
    end
  end


end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password_digest, :password, :role_id, :site_id

  # relationships
  belongs_to :role
  belongs_to :site

  # authentication
  has_secure_password

  # validations
  validates_presence_of :email, :on => :create
  validates_presence_of :password, :on => :create
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery



  def get_site
    @site = Site.find(params[:site_id])
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  def index
    @sites = Site.all
    @site = Site.new
  end
  def create
    @site = Site.new(params[:site])
    if @site.save
      flash[:notice] = "Site created"
    else
      flash[:error] = "Site not created"
    end
    redirect_to root_path
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_filter :get_site

  def index
    @complete_tasks = @site.complete_tasks
    @incomplete_tasks = @site.incomplete_tasks
    @task = @site.tasks.build
  end
  def show
    @task = Task.find(params[:id])
  end
  def create
    @task = @site.tasks.build(params[:task])
    if @task.save
      flash[:notice] = "Task created"
    else
      flash[:error] = "Task not created"
    end
    redirect_to site_tasks_path(@site)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Manage</title>
    <%= include_gon %>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <ul class="nav">
            <li><%= link_to "Sites", root_path %></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="container-fluid">
      <%= yield %>
    </div>
  </body>
</html>

app/views/sites/index.html.erb
<div class="row-fluid">
  <div class="span4">
    <h1>Sites</h1>
  </div>
  <div class="span4">
  </div>
  <div class="span4">
    <%= form_for @site, :html => {:class => "form-inline"} do |f| %>
      <%= f.text_field :title, "placeholder" => "New Site Title" %>

      <%= f.submit "Create Site", :class => "btn btn-primary" %>
    <% end %>
  </div>
</div>

<table class="table table-striped table-condensed sites">
  <thead>
    <tr>
      <th>ID</th>
      <th>Title</th>
      <th>Tasks</th>
    </tr>
  </thead>
  <tbody>
    <% @sites.each do |s| %>
      <tr>
        <td><%= s.id %></td>
        <td><%= link_to s.title, site_tasks_path(s) %></td>
        <td><%= s.tasks.size %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tasks/_tasks_rows.html.erb
<% tasks.each do |t| %>
  <tr style="background-color: <%= t.row_color %>">
    <td><%= t.id %></td>
    <td><%= link_to t.title, site_task_path(@site, t) %></td>
    <td><%= t.status.status %></td>
  </tr>
<% end %>

app/views/tasks/index.html.erb
<div class="row-fluid">
  <div class="span4">
    <h1>Tasks for <%= @site.title %></h1>
  </div>
  <div class="span8">
  </div>
</div>

<div class="row-fluid">
  <div class="span4">
    <%= form_for [@site, @task], :html => {:class => "full"} do |f| %>
      <%= f.label :title%>
      <%= f.text_field :title %>

      <%= f.label :body %>
      <%= f.text_area :body %>

      <%= select_tag "task[status_id]", options_for_select(Status.all.collect{ |s| [s.status, s.id] }) %>


      <div class="form-actions">
        <%= f.submit "Create Task", :class => "btn btn-primary" %>
      </div>
    <% end %>
  </div>
  <div class="span8">
    <h1>Incomplete</h1>
    <table class="table">
      <thead>
        <tr>
          <th>ID</th>
          <th>Title</th>
          <th>Status</th>
        </tr>
      </thead>
      <tbody>
        <%= render :partial => "tasks_rows", :locals => {:tasks => @incomplete_tasks} %>
      </tbody>
    </table>

    <h1>Complete</h1>
    <table class="table">
      <thead>
        <tr>
          <th>ID</th>
          <th>Title</th>
          <th>Status</th>
        </tr>
      </thead>
      <tbody>
        <%= render :partial => "tasks_rows", :locals => {:tasks => @complete_tasks} %>
      </tbody>
    </table>
  </div>
</div>

app/views/tasks/show.html.erb
<div class="row-fluid">
  <div class="span4">
    <div class="page-header">
      <h1>Task #<%= @task.id %></h1>
    </div>
    <%= form_for [@site, @task], :html => {:class => "full"} do |f| %>
      <%= f.label :title %>
      <%= f.text_field :title %>

      <%= f.label :body %>
      <%= f.text_area :body %>

      <%= select_tag "task[status_id]", options_for_select(Status.all.collect{ |s| [s.status, s.id] }) %>

      <div class="form-actions">
        <%= f.submit "Update Task", :class => "btn btn-primary" %>
      </div>
    <% end %>
  </div>
  <div class="span8">
    <div class="page-header">
      <h1>Comments</h1>
    </div>
  </div>
</div>